import { InferGetStaticPropsType } from "next";
import Head from "next/head";
import { useState } from "react";
import { toast } from "react-hot-toast";
import { prisma } from "~/server/db";
import { api } from "~/utils/api";

export default function Page(props: InferGetStaticPropsType<typeof getStaticProps>) {
  const { event } = props;
  if (!event) {
    return;
  }

  const { mutateAsync: comment, isLoading: commenting } = api.event.sendComment.useMutation();

  const [msg, setMsg] = useState("");

  const sendComment = async () => {
    if (commenting) {
      return;
    }
    toast.loading("sending comments...");
    const { success } = await comment({
      content: msg,
      slug: event.slug,
      sender: "anonymous",
      time: String(Date.now()),
    });
    toast.dismiss();
    success ? toast.success("successfully sent the comment!") : toast.error("sending failed! try again later");
  };
  return (
    <>
      <Head>
        <title>{event.slug}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-[#DDB500]">
        <div className="container flex flex-col justify-center items-center py-16 px-4 sm:gap-12">
          <h1 className="text-2xl font-extrabold tracking-tight text-white drop-shadow-lg sm:text-[5rem]">
            send anonymous comment to
          </h1>
          <h1 className="text-5xl font-extrabold tracking-tight text-white drop-shadow-lg sm:text-[5rem]">
            {event.user.name}
          </h1>
          <textarea
            className="p-5 mt-16 mb-2 w-3/4 h-32 text-lg rounded-lg border-none sm:mt-10 sm-mb-0 sm:w-1/2 drop-shadow-lg"
            maxLength={180}
            onChange={(e) => setMsg(e.currentTarget.value)}
            placeholder="just speak from your heart...."
          />
          <p className="mb-10 font-bold text-white sm:-mt-10 drop-shadow">{msg.length}/180 charactors</p>
          <button
            className="py-2 px-4 sm:w-1/4 w-1/2  text-xl font-bold text-gray-800 bg-white rounded-xl border-2 border drop-shadow border-[#CCA400] hover:bg-gray-100"
            onClick={() => void sendComment()}
          >
            Send <span className="ml-4 text-2xl">🚀</span>
          </button>
        </div>
      </main>
    </>
  );
}
// This function gets called at build time
export async function getStaticPaths() {
  // Call an external API endpoint to get posts
  const events = await prisma.event.findMany({
    select: {
      slug: true,
    },
  });

  // Get the paths we want to pre-render based on posts
  const paths = events.map((e) => ({
    params: { slug: e.slug },
  }));

  // We'll pre-render only these paths at build time.
  // { fallback: false } means other routes should 404.
  return { paths, fallback: "blocking" };
}

// This also gets called at build time
export async function getStaticProps(props: { params: { slug: string } }) {
  // params contains the post `id`.
  // If the route is like /posts/1, then params.id is 1
  const { params } = props;
  const event = await prisma.event.findUnique({
    where: {
      slug: params.slug,
    },
    select: {
      slug: true,
      user: {
        select: {
          name: true,
          image: true,
        },
      },
    },
  });

  // Pass post data to the page via props
  return { props: { event } };
}
