import Head from "next/head";
import { prisma } from "~/server/db";

export default function Page(props: { event: { user: { name: string; image: string }; slug: string } | null }) {
  const { event } = props;
  if (!event) {
    return;
  }
  return (
    <>
      <Head>
        <title>{event.slug}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-[#DDB500]">
        <div className="container flex flex-col gap-12 justify-center items-center py-16 px-4">
          <h1 className="text-2xl font-extrabold tracking-tight text-white drop-shadow-lg sm:text-[5rem]">
            send anonymous comment to {event.user.name}
          </h1>
          <textarea
            className="p-5 mt-10 w-1/2 h-32 text-lg rounded-lg border-none drop-shadow-lg"
            placeholder="just speak from your heart...."
          />
          <button className="py-2 px-4 w-1/4 text-xl font-bold text-gray-800 bg-white rounded-xl border-2 border drop-shadow border-[#CCA400] hover:bg-gray-100">
            Send <span className="ml-4 text-2xl">🚀</span>
          </button>
        </div>
      </main>
    </>
  );
}
// This function gets called at build time
export async function getStaticPaths() {
  // Call an external API endpoint to get posts
  const events = await prisma.event.findMany({
    select: {
      slug: true,
    },
  });

  // Get the paths we want to pre-render based on posts
  const paths = events.map((e) => ({
    params: { slug: e.slug },
  }));

  // We'll pre-render only these paths at build time.
  // { fallback: false } means other routes should 404.
  return { paths, fallback: false };
}

// This also gets called at build time
export async function getStaticProps(payload: { slug: string }) {
  // params contains the post `id`.
  // If the route is like /posts/1, then params.id is 1
  const event = await prisma.event.findUnique({
    where: {
      slug: payload.slug,
    },
    select: {
      slug: true,
      user: {
        select: {
          name: true,
          image: true,
        },
      },
    },
  });

  // Pass post data to the page via props
  return { props: { event } };
}
