import { Comment } from "@prisma/client";
import { GetServerSideProps, InferGetServerSidePropsType } from "next";
import { signOut } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/router";
import { toast } from "react-hot-toast";
import { getServerAuthSession } from "~/server/auth";
import { prisma } from "~/server/db";
import { getDate } from "~/utils/date";
import { getBaseUrl } from "~/utils/url";

export default function Dashboard({ comments, slug }: InferGetServerSidePropsType<typeof getServerSideProps>) {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>dashboard</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button
        onClick={() => void signOut()}
        className="py-2 px-4 mt-5 ml-5 font-semibold text-white rounded drop-shadow-lg bg-sky-500"
      >
        logout
      </button>
      <main className="flex flex-col justify-center items-center w-full">
        <div className="flex flex-col py-20 px-5 w-full min-h-screen sm:w-4/5 sm:border-l-4 sm:border-indigo-500">
          <h1 className="mb-20 w-full text-5xl font-extrabold text-center text-gray-800 drop-shadow-lg">
            These are all the anonymous responses!
          </h1>
          <div className="flex flex-col w-full sm:flex-row">
            <div className="flex flex-col w-full">
              {comments && comments.length > 0
                ? (
                  <>
                    {comments.map((el, index) => (
                      <div
                        className="flex py-2 px-4 mb-5 w-full rounded sm:w-11/12 bg-sky-100 drop-shadow-lg"
                        key={index}
                      >
                        <p className="w-4/5 font-medium text-left sm:text-xl text-[16px] sm:w-4/3">
                          {el.content}
                        </p>
                        <p className="w-1/5 text-xs text-right text-gray-600 sm:w-1/3 sm:text-sm">
                          {getDate(el.created_At ? Number(el.created_At) : null)}
                        </p>
                      </div>
                    ))}
                  </>
                )
                : (
                  <p className="py-2 px-4 w-3/4 text-xl font-medium text-left bg-red-100 rounded drop-shadow-lg">
                    opps! no responses yet
                  </p>
                )}
            </div>
            <div className="flex flex-col items-center mt-20 w-full rounded-xl sm:mt-0 sm:w-2/5 sm:min-h-screen h-[550px] bg-sky-700 drop-shadow-xl">
              <p className="px-2 mt-20 w-full text-2xl font-semibold text-center text-white sm:px-10 sm:text-4xl drop-shadow-lg">
                Share your link and see how many responses you can get!
              </p>
              <div className="flex justify-center items-center mt-10 w-full">
                <p className="p-2 py-6 pl-4 w-4/12 text-6xl bg-white rounded-full sm:pl-0 sm:text-9xl">📣</p>
              </div>
              <p className="py-2 px-1 mx-10 mt-10 w-3/4 text-lg font-semibold text-gray-600 bg-white rounded-xl sm:py-3 sm:px-5 sm:text-2xl">
                {getBaseUrl()}/{slug}
              </p>
              <div className="flex gap-4 justify-center items-center w-11/12 sm:gap-0 sm:justify-around sm:w-5/6">
                <button
                  className="py-2 mt-10 w-full text-xl font-semibold text-white rounded-2xl border-2 border-white sm:mx-10 sm:text-2xl hover:scale-105"
                  onClick={() => {
                    toast.success("link copied to clipboard!");
                    navigator.clipboard.writeText(
                      `${getBaseUrl()}/${slug}`,
                    );
                  }}
                >
                  copy link
                </button>
                <button
                  className="py-2 mt-10 w-full text-xl font-semibold text-white rounded-2xl border-2 border-white sm:text-2xl hover:scale-105"
                  onClick={() => void router.push(`${getBaseUrl()}/${slug}`)}
                >
                  visit page
                </button>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}

export const getServerSideProps: GetServerSideProps<{
  comments: Comment[];
  slug: string;
}> = async (ctx) => {
  const session = await getServerAuthSession(ctx);
  const slug = session?.user.event?.slug;

  if (!slug) {
    return { props: { comments: [], slug: "" } };
  }
  const comments = (await prisma.event.findUnique({
    where: {
      slug,
    },
    select: {
      comments: true,
    },
  }))?.comments;

  return { props: { comments: comments ? comments : [], slug } };
};
