import { Comment } from "@prisma/client";
import { GetServerSideProps, InferGetServerSidePropsType } from "next";
import { signOut } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/router";
import { toast } from "react-hot-toast";
import { getServerAuthSession } from "~/server/auth";
import { prisma } from "~/server/db";
import { getDate } from "~/utils/date";
import { getBaseUrl } from "~/utils/url";

export default function Dashboard({ comments, slug }: InferGetServerSidePropsType<typeof getServerSideProps>) {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>dashboard</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col justify-center items-center w-full">
        <button
          onClick={() => void signOut()}
          className="py-2 px-4 mt-10 font-semibold text-white rounded ml-[1500px] drop-shadow-lg bg-sky-500"
        >
          logout
        </button>
        <div className="flex flex-col py-20 px-10 mt-10 w-4/5 min-h-screen border-l-4 border-indigo-500">
          <h1 className="mb-32 w-full text-2xl font-extrabold tracking-tight text-center text-gray-800 drop-shadow-lg sm:text-[5rem]">
            These are all the anonymous responses!
          </h1>
          <div className="flex w-full">
            <div className="flex flex-col w-3/5">
              {comments && comments.length > 0
                ? (
                  <>
                    {comments.map((el, index) => (
                      <div className="flex py-2 px-4 mb-5 w-11/12 rounded bg-sky-100 drop-shadow-lg">
                        <p
                          className="w-5/12 text-xl font-medium text-left"
                          key={index}
                        >
                          {el.content}
                        </p>
                        <p className="w-5/12 text-sm text-right text-gray-600 bg-sky-100">
                          {getDate(el.created_At ? Number(el.created_At) : null)}
                        </p>
                      </div>
                    ))}
                  </>
                )
                : (
                  <p className="py-2 px-4 w-3/4 text-xl font-medium text-left bg-red-100 rounded drop-shadow-lg">
                    opps! no responses yet
                  </p>
                )}
            </div>
            <div className="flex flex-col w-2/5 min-h-screen rounded-xl bg-sky-700 drop-shadow-xl">
              <p className="px-10 mt-20 w-full text-4xl font-semibold text-center text-white drop-shadow-lg">
                Share your link and see how many responses you can get!
              </p>
              <div className="flex justify-center items-center mt-10 w-full">
                <p className="p-2 py-6 w-4/12 text-9xl bg-white rounded-full">📣</p>
              </div>
              <p className="py-3 px-5 mx-10 mt-10 w-3/4 text-2xl font-semibold text-gray-600 bg-white rounded-xl">
                {getBaseUrl()}/{slug}
              </p>
              <div className="flex justify-around items-center w-5/6">
                <button
                  className="py-2 mx-10 mt-10 w-1/3 text-2xl font-semibold text-white rounded-2xl border-2 border-white hover:scale-105"
                  onClick={() => {
                    toast.success("link copied to clipboard!");
                    navigator.clipboard.writeText(
                      `${getBaseUrl()}/${slug}`,
                    );
                  }}
                >
                  copy link
                </button>
                <button
                  className="py-2 mx-10 mt-10 w-1/3 text-2xl font-semibold text-white rounded-2xl border-2 border-white hover:scale-105"
                  onClick={() => void router.push(`${getBaseUrl()}/${slug}`)}
                >
                  visit page
                </button>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}

export const getServerSideProps: GetServerSideProps<{
  comments: Comment[];
  slug: string;
}> = async (ctx) => {
  const session = await getServerAuthSession(ctx);
  const slug = session?.user.event?.slug;

  if (!slug) {
    return { props: { comments: [], slug: "" } };
  }
  const comments = (await prisma.event.findUnique({
    where: {
      slug,
    },
    select: {
      comments: true,
    },
  }))?.comments;

  return { props: { comments: comments ? comments : [], slug } };
};
