import debounce from "lodash.debounce";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import { useCallback, useEffect, useRef, useState } from "react";
import { api } from "~/utils/api";
import { keywords } from "~/utils/data";
import { slugRegex } from "~/utils/validation";

export default function Home() {
  const { data: sessionData } = useSession();
  const [validating, setValidating] = useState<boolean>(false);
  const [isValid, setIsValid] = useState<boolean>(false);
  const [slugError, setSLugError] = useState<string | null>(null);
  const [slugValue, setSlugValue] = useState<string>("");

  const { mutateAsync: createEvent, isLoading: onGoing } = api.event.create.useMutation();
  const { mutateAsync: checkSlug, isLoading: checkingSlug } = api.event.slugAvailable.useMutation();

  const checkSlugValue = useCallback(
    debounce(async (slug: string) => {
      setValidating(true);
      const { valueValid, valueError } = slugRegex(slug);
      if (!valueValid) {
        setIsValid(false);
        setValidating(false);
        setSLugError(valueError);
        return;
      }
      if (slug) {
        if (keywords.includes(slug)) {
          setIsValid(false);
          setValidating(false);
          setSLugError("This username cannot be used");
          return;
        }

        const { isSlugAvailable } = await checkSlug({ slug });
        if (!isSlugAvailable) {
          setIsValid(false);
          setSLugError("title aready occupied");
        } else {
          setIsValid(true);
          setSLugError(null);
        }
      }
      setValidating(false);
    }, 500),
    [],
  );

  useEffect(() => {
    // this is done to avoid displaying errors in the initial state
    slugValue !== "" && checkSlugValue(slugValue);
    // eslint-disable-next-line
  }, [slugValue, checkSlug]);

  const createPage = async () => {
    if (!sessionData) {
      console.log("validating");
      return;
    }

    if (validating || checkingSlug || onGoing) {
      return;
    }

    if (slugError || !isValid) {
      return;
    }
    await createEvent({ slug: slugValue, userId: sessionData.user.id });
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-[#DDB500]">
        <div className="container flex flex-col gap-12 justify-center items-center py-16 px-4">
          <h1 className="text-5xl font-extrabold tracking-tight text-white drop-shadow-lg sm:text-[5rem]">
            Hear what your freinds have to say
          </h1>
          <h1 className="-mt-10 text-5xl font-extrabold tracking-tight text-white drop-shadow-lg sm:text-[5rem]">
            anonymously!
          </h1>
          <div className="flex flex-col gap-4 justify-center items-center w-full">
            {sessionData
              ? (
                <>
                  <div className="flex items-center p-5 w-1/3 bg-white rounded-2xl shodow-lg">
                    <input
                      className="w-1/3 text-xl border"
                      placeholder="title"
                      onChange={(e) => {
                        setSlugValue(e.currentTarget.value);
                      }}
                    />
                    <p className="w-1/3 text-xl font-semibold text-gray-500">/say.me</p>
                    <button
                      className="py-2 px-4 w-1/3 text-xl font-semibold text-center text-white bg-gray-800 rounded-lg hover:bg-gray-600"
                      onClick={() => void createPage()}
                    >
                      create page
                    </button>
                  </div>
                  {!isValid && slugError
                    && (
                      <p className="p-1 w-1/3 text-xs font-semibold text-red-500 bg-black rounded">
                        {validating || checkingSlug ? "validation title..." : slugError}
                      </p>
                    )}
                </>
              )
              : (
                <button
                  className="py-3 px-10 text-xl font-semibold text-white no-underline bg-gray-800 rounded-full transition hover:bg-white/20"
                  onClick={() => void signIn()}
                >
                  Sign In
                </button>
              )}
          </div>
        </div>
      </main>
    </>
  );
}
